#!/bin/bash
#### Special vars ####
echo "All variables passed to script: $@"
echo "Number of variables passed: $#"
echo "First variable: $1"
echo "Script name: $0"
echo "who is running this:$USER"
echo "which dicretiory is:$PWD"
