#!/bin/bash
#### Special vars ####
echo "All variables passed to script: $@"
echo "Number of variables passed: $#"
echo "First variable: $1"
echo "Script name: $0"
echo "who is running this:$USER"
echo "which dicretiory is:$PWD"
echo "Home Directory:$HOME"
echo "PID of current script:$$"
sleep 5 &
echo "PID of the background command running just now:$!"
wait $!
echo "Line number: $LINENO"
