#!/bin/bash

### Speical chars ###
echo "All variables passed to script: $@"
echo "Number of variables passed to script: $#"
echo "First variale: $1"
echo "Script name: $0"
echo "Who is running this: $USER"
echo "Which directory: $PWD"
echo "Home directory: $HOME"
echo "PID of the current script: $$"
Sleep 5 &
echo "PID of the background command running just now: $!'
Wait $!
echo "Line Number: LINENO"
